//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniWave.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALT_KATEGORİ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALT_KATEGORİ()
        {
            this.URUN = new HashSet<URUN>();
        }
    
        public int AltKategoriID { get; set; }
        public string AltKategoriAdi { get; set; }
        public Nullable<int> AnaKategoriID { get; set; }
    
        public virtual KATEGORİ KATEGORİ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URUN> URUN { get; set; }
    }
}
