//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniWave.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORİLER
    {
        public int FavoriID { get; set; }
        public Nullable<int> FavoriUrunID { get; set; }
        public Nullable<int> FavoriUrunSahibiID { get; set; }
    
        public virtual URUN URUN { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
