//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniWave.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUN()
        {
            this.FAVORİLER = new HashSet<FAVORİLER>();
        }
    
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string UrunResimPath { get; set; }
        public string UrunAciklama { get; set; }
        public int UrunMagazaID { get; set; }
        public Nullable<int> UrunKategoriID { get; set; }
        public Nullable<int> UrunFiyat { get; set; }
    
        public virtual ALT_KATEGORİ ALT_KATEGORİ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORİLER> FAVORİLER { get; set; }
        public virtual MAGAZA MAGAZA { get; set; }
    }
}
