//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniWave.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Miniwave : DbContext
    {
        public Miniwave()
            : base("name=Miniwave")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALT_KATEGORİ> ALT_KATEGORİ { get; set; }
        public virtual DbSet<FAVORİLER> FAVORİLER { get; set; }
        public virtual DbSet<KATEGORİ> KATEGORİ { get; set; }
        public virtual DbSet<MAGAZA> MAGAZA { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<URUN> URUN { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    
        public virtual ObjectResult<EnPopulerUrunuBul_Result> EnPopulerUrunuBul()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnPopulerUrunuBul_Result>("EnPopulerUrunuBul");
        }
    
        public virtual ObjectResult<FavoriGoruntule_Result> FavoriGoruntule(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FavoriGoruntule_Result>("FavoriGoruntule", userIDParameter);
        }
    
        public virtual ObjectResult<KategorideEnPopulerUrunuBul_Result> KategorideEnPopulerUrunuBul(Nullable<int> kategori)
        {
            var kategoriParameter = kategori.HasValue ?
                new ObjectParameter("Kategori", kategori) :
                new ObjectParameter("Kategori", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KategorideEnPopulerUrunuBul_Result>("KategorideEnPopulerUrunuBul", kategoriParameter);
        }
    
        public virtual ObjectResult<KategoridekiUrunler_Result> KategoridekiUrunler(Nullable<int> kategori)
        {
            var kategoriParameter = kategori.HasValue ?
                new ObjectParameter("Kategori", kategori) :
                new ObjectParameter("Kategori", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KategoridekiUrunler_Result>("KategoridekiUrunler", kategoriParameter);
        }
    
        public virtual ObjectResult<KategoridekiUrunlerdeEnYeniUrunler_Result> KategoridekiUrunlerdeEnYeniUrunler(Nullable<int> kategori)
        {
            var kategoriParameter = kategori.HasValue ?
                new ObjectParameter("Kategori", kategori) :
                new ObjectParameter("Kategori", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KategoridekiUrunlerdeEnYeniUrunler_Result>("KategoridekiUrunlerdeEnYeniUrunler", kategoriParameter);
        }
    
        public virtual ObjectResult<KategoridekiUrunleriEnDusukFiyataGoreSirala_Result> KategoridekiUrunleriEnDusukFiyataGoreSirala(Nullable<int> kategori)
        {
            var kategoriParameter = kategori.HasValue ?
                new ObjectParameter("Kategori", kategori) :
                new ObjectParameter("Kategori", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KategoridekiUrunleriEnDusukFiyataGoreSirala_Result>("KategoridekiUrunleriEnDusukFiyataGoreSirala", kategoriParameter);
        }
    
        public virtual ObjectResult<KategoridekiUrunleriEnYuksekFiyataGoreSirala_Result> KategoridekiUrunleriEnYuksekFiyataGoreSirala(Nullable<int> kategori)
        {
            var kategoriParameter = kategori.HasValue ?
                new ObjectParameter("Kategori", kategori) :
                new ObjectParameter("Kategori", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KategoridekiUrunleriEnYuksekFiyataGoreSirala_Result>("KategoridekiUrunleriEnYuksekFiyataGoreSirala", kategoriParameter);
        }
    
        public virtual int KategorideUrunSayisi(Nullable<int> kategori, ObjectParameter sayi)
        {
            var kategoriParameter = kategori.HasValue ?
                new ObjectParameter("Kategori", kategori) :
                new ObjectParameter("Kategori", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KategorideUrunSayisi", kategoriParameter, sayi);
        }
    
        public virtual ObjectResult<TumUrunlerdeEnYeniUrunler_Result> TumUrunlerdeEnYeniUrunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TumUrunlerdeEnYeniUrunler_Result>("TumUrunlerdeEnYeniUrunler");
        }
    
        public virtual ObjectResult<TumUrunleriEnDusukFiyataGoreSirala_Result> TumUrunleriEnDusukFiyataGoreSirala()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TumUrunleriEnDusukFiyataGoreSirala_Result>("TumUrunleriEnDusukFiyataGoreSirala");
        }
    
        public virtual ObjectResult<TumUrunleriEnYuksekFiyataGoreSirala_Result> TumUrunleriEnYuksekFiyataGoreSirala()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TumUrunleriEnYuksekFiyataGoreSirala_Result>("TumUrunleriEnYuksekFiyataGoreSirala");
        }
    
        public virtual int TumUrunlerinSayisi(ObjectParameter sayi)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumUrunlerinSayisi", sayi);
        }
    
        public virtual ObjectResult<UrunArama_Result> UrunArama(string urunAdi)
        {
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunArama_Result>("UrunArama", urunAdiParameter);
        }
    
        public virtual int UrunEkle(string urunAdi, string urunResimPath, string urunAciklama, Nullable<int> urunMagaza, Nullable<int> urunKategori, Nullable<int> urunFiyat)
        {
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var urunResimPathParameter = urunResimPath != null ?
                new ObjectParameter("UrunResimPath", urunResimPath) :
                new ObjectParameter("UrunResimPath", typeof(string));
    
            var urunAciklamaParameter = urunAciklama != null ?
                new ObjectParameter("UrunAciklama", urunAciklama) :
                new ObjectParameter("UrunAciklama", typeof(string));
    
            var urunMagazaParameter = urunMagaza.HasValue ?
                new ObjectParameter("UrunMagaza", urunMagaza) :
                new ObjectParameter("UrunMagaza", typeof(int));
    
            var urunKategoriParameter = urunKategori.HasValue ?
                new ObjectParameter("UrunKategori", urunKategori) :
                new ObjectParameter("UrunKategori", typeof(int));
    
            var urunFiyatParameter = urunFiyat.HasValue ?
                new ObjectParameter("UrunFiyat", urunFiyat) :
                new ObjectParameter("UrunFiyat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UrunEkle", urunAdiParameter, urunResimPathParameter, urunAciklamaParameter, urunMagazaParameter, urunKategoriParameter, urunFiyatParameter);
        }
    
        public virtual int UrunSil(Nullable<int> urunID)
        {
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UrunSil", urunIDParameter);
        }
    }
}
